// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    kind,
    payload,
    run_at,
    max_retries
)
VALUES (
    $1,
    $2,
    COALESCE($3, NOW()),
    $4
)
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type CreateJobParams struct {
	Kind       string
	Payload    []byte
	RunAt      interface{}
	MaxRetries int32
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Kind,
		arg.Payload,
		arg.RunAt,
		arg.MaxRetries,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
FROM jobs
WHERE ($1::job_status IS NULL OR status = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListJobsParams struct {
	Column1 JobStatus
	Limit   int32
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.LockedBy,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
