// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingJob = `-- name: CancelPendingJob :one
UPDATE jobs
SET status = 'cancelled',
    updated_at = NOW()
WHERE id = $1
  AND status = 'pending'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

func (q *Queries) CancelPendingJob(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, cancelPendingJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const claimNextJob = `-- name: ClaimNextJob :one
WITH claimed AS (
    SELECT id
    FROM jobs
    WHERE status = 'pending'
      AND run_at <= clock_timestamp()
    ORDER BY priority DESC, run_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status = 'running',
    locked_by = $1::text,
    locked_until = clock_timestamp() + ($2::int * INTERVAL '1 second'),
    attempted_at = clock_timestamp(),
    updated_at = clock_timestamp()
FROM claimed
WHERE jobs.id = claimed.id
RETURNING jobs.id, jobs.kind, jobs.payload, jobs.status, jobs.priority, jobs.run_at, jobs.created_at, jobs.updated_at, jobs.attempted_at, jobs.completed_at, jobs.retry_count, jobs.max_retries, jobs.error_message, jobs.locked_by, jobs.locked_until
`

type ClaimNextJobParams struct {
	WorkerID     string
	LeaseSeconds int32
}

func (q *Queries) ClaimNextJob(ctx context.Context, arg ClaimNextJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, claimNextJob, arg.WorkerID, arg.LeaseSeconds)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (
    kind,
    payload,
    run_at,
    max_retries
)
VALUES (
    $1,
    $2,
    COALESCE($3, NOW()),
    $4
)
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type CreateJobParams struct {
	Kind       string
	Payload    []byte
	RunAt      interface{}
	MaxRetries int32
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Kind,
		arg.Payload,
		arg.RunAt,
		arg.MaxRetries,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const getJobByID = `-- name: GetJobByID :one
SELECT id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
FROM jobs
WHERE id = $1
`

func (q *Queries) GetJobByID(ctx context.Context, id pgtype.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJobByID, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const listJobs = `-- name: ListJobs :many
SELECT id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
FROM jobs
ORDER BY created_at DESC
LIMIT $1
`

func (q *Queries) ListJobs(ctx context.Context, jobLimit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, jobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.LockedBy,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobsByStatus = `-- name: ListJobsByStatus :many
SELECT id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
FROM jobs
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListJobsByStatusParams struct {
	Status   JobStatus
	JobLimit int32
}

func (q *Queries) ListJobsByStatus(ctx context.Context, arg ListJobsByStatusParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobsByStatus, arg.Status, arg.JobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.LockedBy,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJobCompleted = `-- name: MarkJobCompleted :one
UPDATE jobs
SET status = 'completed',
    completed_at = clock_timestamp(),
    updated_at = clock_timestamp(),
    locked_by = NULL,
    locked_until = NULL
WHERE id = $1
  AND locked_by = $2::text
  AND status = 'running'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type MarkJobCompletedParams struct {
	ID       pgtype.UUID
	WorkerID string
}

func (q *Queries) MarkJobCompleted(ctx context.Context, arg MarkJobCompletedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobCompleted, arg.ID, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const markJobDead = `-- name: MarkJobDead :one
UPDATE jobs
SET status = 'dead',
    retry_count = retry_count + 1,
    error_message = $1::text,
    updated_at = clock_timestamp(),
    locked_by = NULL,
    locked_until = NULL
WHERE id = $2
  AND locked_by = $3::text
  AND status = 'running'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type MarkJobDeadParams struct {
	ErrorMessage string
	ID           pgtype.UUID
	WorkerID     string
}

func (q *Queries) MarkJobDead(ctx context.Context, arg MarkJobDeadParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobDead, arg.ErrorMessage, arg.ID, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const markJobFailed = `-- name: MarkJobFailed :one
UPDATE jobs
SET status = 'failed',
    error_message = $1::text,
    updated_at = clock_timestamp(),
    locked_by = NULL,
    locked_until = NULL
WHERE id = $2
  AND locked_by = $3::text
  AND status = 'running'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type MarkJobFailedParams struct {
	ErrorMessage string
	ID           pgtype.UUID
	WorkerID     string
}

func (q *Queries) MarkJobFailed(ctx context.Context, arg MarkJobFailedParams) (Job, error) {
	row := q.db.QueryRow(ctx, markJobFailed, arg.ErrorMessage, arg.ID, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const ping = `-- name: Ping :one
SELECT 1
`

func (q *Queries) Ping(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, ping)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const reclaimExpiredJobs = `-- name: ReclaimExpiredJobs :many
WITH expired AS (
    SELECT id,
           CASE
               WHEN retry_count + 1 >= max_retries THEN 'dead'::job_status
               ELSE 'pending'::job_status
           END AS next_status
    FROM jobs
    WHERE status = 'running'
      AND locked_until < clock_timestamp()
    ORDER BY locked_until ASC
    LIMIT $1
    FOR UPDATE SKIP LOCKED
)
UPDATE jobs
SET status = expired.next_status,
    retry_count = retry_count + 1,
    error_message = CASE
        WHEN expired.next_status = 'dead'::job_status THEN 'job lease expired and max retries exhausted'
        ELSE 'job lease expired; reclaiming for retry'
    END,
    run_at = CASE
        WHEN expired.next_status = 'pending'::job_status THEN clock_timestamp()
        ELSE jobs.run_at
    END,
    updated_at = clock_timestamp(),
    locked_by = NULL,
    locked_until = NULL
FROM expired
WHERE jobs.id = expired.id
RETURNING jobs.id, jobs.kind, jobs.payload, jobs.status, jobs.priority, jobs.run_at, jobs.created_at, jobs.updated_at, jobs.attempted_at, jobs.completed_at, jobs.retry_count, jobs.max_retries, jobs.error_message, jobs.locked_by, jobs.locked_until
`

func (q *Queries) ReclaimExpiredJobs(ctx context.Context, jobLimit int32) ([]Job, error) {
	rows, err := q.db.Query(ctx, reclaimExpiredJobs, jobLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Payload,
			&i.Status,
			&i.Priority,
			&i.RunAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AttemptedAt,
			&i.CompletedAt,
			&i.RetryCount,
			&i.MaxRetries,
			&i.ErrorMessage,
			&i.LockedBy,
			&i.LockedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renewJobLease = `-- name: RenewJobLease :one
UPDATE jobs
SET locked_until = clock_timestamp() + ($1::int * INTERVAL '1 second'),
    updated_at = clock_timestamp()
WHERE id = $2
  AND locked_by = $3::text
  AND status = 'running'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type RenewJobLeaseParams struct {
	LeaseSeconds int32
	ID           pgtype.UUID
	WorkerID     string
}

func (q *Queries) RenewJobLease(ctx context.Context, arg RenewJobLeaseParams) (Job, error) {
	row := q.db.QueryRow(ctx, renewJobLease, arg.LeaseSeconds, arg.ID, arg.WorkerID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}

const scheduleJobRetry = `-- name: ScheduleJobRetry :one
UPDATE jobs
SET status = 'pending',
    retry_count = retry_count + 1,
    error_message = $1::text,
    run_at = clock_timestamp() + ($2::int * INTERVAL '1 second'),
    updated_at = clock_timestamp(),
    locked_by = NULL,
    locked_until = NULL
WHERE id = $3
  AND locked_by = $4::text
  AND status = 'running'
RETURNING id, kind, payload, status, priority, run_at, created_at, updated_at, attempted_at, completed_at, retry_count, max_retries, error_message, locked_by, locked_until
`

type ScheduleJobRetryParams struct {
	ErrorMessage string
	DelaySeconds int32
	ID           pgtype.UUID
	WorkerID     string
}

func (q *Queries) ScheduleJobRetry(ctx context.Context, arg ScheduleJobRetryParams) (Job, error) {
	row := q.db.QueryRow(ctx, scheduleJobRetry,
		arg.ErrorMessage,
		arg.DelaySeconds,
		arg.ID,
		arg.WorkerID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.Status,
		&i.Priority,
		&i.RunAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AttemptedAt,
		&i.CompletedAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.ErrorMessage,
		&i.LockedBy,
		&i.LockedUntil,
	)
	return i, err
}
